from django.urls import path

from .views import (
    blog_create_view,
    blog_delete_view,
    blog_list_view,
    blog_update_view,
    create_options_view,
    export_posts_csv_view,
    export_posts_xlsx_view,
    export_single_user_posts_csv_view,
    export_single_user_posts_xlsx_view,
    export_user_summary_csv_view,
    export_user_summary_xlsx_view,
    home_view,
    landing_view,
    organization_view,
    post_create_view,
    post_delete_view,
    post_list_view,
    post_update_view,
    project_create_view,
    project_delete_view,
    project_list_view,
    project_update_view,
    profile_view,
    research_paper_create_view,
    research_paper_delete_view,
    research_paper_list_view,
    research_paper_update_view,
    switch_mode_view,
)

app_name = "searcher"

urlpatterns = [
    path("", home_view, name="search"),
    path("home/", home_view, name="home"),
    path("profile/", profile_view, name="profile"),
    path("create-options/", create_options_view, name="create-options"),
    path("posts/", post_list_view, name="posts"),
    path("posts/new/", post_create_view, name="post-create"),
    path("posts/<int:post_id>/edit/", post_update_view, name="post-edit"),
    path("posts/<int:post_id>/delete/", post_delete_view, name="post-delete"),
    path("projects/", project_list_view, name="projects"),
    path("projects/new/", project_create_view, name="project-create"),
    path("projects/<int:project_id>/edit/", project_update_view, name="project-edit"),
    path("projects/<int:project_id>/delete/", project_delete_view, name="project-delete"),
    path("blogs/", blog_list_view, name="blogs"),
    path("blogs/new/", blog_create_view, name="blog-create"),
    path("blogs/<int:blog_id>/edit/", blog_update_view, name="blog-edit"),
    path("blogs/<int:blog_id>/delete/", blog_delete_view, name="blog-delete"),
    path("research/", research_paper_list_view, name="research"),
    path("research/new/", research_paper_create_view, name="research-create"),
    path("research/<int:paper_id>/edit/", research_paper_update_view, name="research-edit"),
    path("research/<int:paper_id>/delete/", research_paper_delete_view, name="research-delete"),
    path("organization/", organization_view, name="organization"),
    path("organization/export/posts.csv", export_posts_csv_view, name="export-posts-csv"),
    path("organization/export/posts.xlsx", export_posts_xlsx_view, name="export-posts-xlsx"),
    path("organization/export/summary.csv", export_user_summary_csv_view, name="export-summary-csv"),
    path("organization/export/summary.xlsx", export_user_summary_xlsx_view, name="export-summary-xlsx"),
    path("organization/export/user/<int:user_id>/posts.csv", export_single_user_posts_csv_view, name="export-user-posts-csv"),
    path("organization/export/user/<int:user_id>/posts.xlsx", export_single_user_posts_xlsx_view, name="export-user-posts-xlsx"),
    path("switch-mode/", switch_mode_view, name="switch-mode"),
    path("landing/", landing_view, name="landing"),
]
