# Generated by Django 6.0.3 on 2026-03-16 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField()),
                ('hashtag', models.CharField(max_length=100)),
                ('profile_name', models.CharField(blank=True, max_length=255)),
                ('total_posts', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='PostResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField()),
                ('post_date', models.DateField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='searcher.searchquery')),
            ],
            options={
                'ordering': ['-post_date', 'id'],
            },
        ),
    ]
